[project]
name = "ibm-ds"
version = "0.1.0"
description = "This repo contains my exercises and assingments necessary for the course completion."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "pandas>=2.3.0",
]
